import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {useState, useEffect} from 'react'
import Logo from '../src/component/logo';
import axios from 'axios';
import Team from '../src/component/team';
import PageHeader from '../src/component/pageHeader';
import PageFooter from '../src/component/customFooter';
export default function Home() {
  const[counter, setCounter] = useState(1);
  const[teams, setTeams] = useState([]);
  const readTeams = ()=>{
    console.log("descargando equipos..");
    axios.get("https://www.thesportsdb.com/api/v1/json/1/search_all_teams.php?l=Spanish%20La%20Liga")
    .then(response =>{
      if (response.stauts = 200){
        const equipos = response.data.teams.map(team =>{
          return {
            id: team.idTeam,
            name: team.strTeam,
            logo: team.strTeamLogo,
            stadium: team.strStadium
          }

        });
        setTeams(equipos);
      }

      
    }).catch(error =>{

    });
  }
  /*setInterval(() => {
    setCounter(counter + 1);
    console.log(counter);
    },1000);
    */
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       
        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>
        <Logo/>
        <button className="button is-primary">Botón</button>
        <button className="button is-danger is-rounded" onClick = {readTeams}>La liga</button>
        <div className = "container">
          <h2>
          <PageHeader title = "New Search" />
          <div className ="colums is-multiline" >
            {teams.map((team, index) =>{
              
              return <Team team ={team} key = {`team-${index}`}/>;
              
            })}
            </div>
          </h2>
        </div>
        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
            <PageFooter/>
      </footer>
    </div>
  )
}
